name: "markov_llm_depth_heads"
method: grid
project: "markov-LLM-depth-heads-attention-ICL_P_Random-optimised-modified-9th_Oct"
parameters:
  chain:
    values: ["icl"]
  order:
    values: [1]
  n_layer:
    values: [2]
  n_head:
    values: [1]
  n_embd:
    values: [16, 32]  # Merged with previous `n_embd`
  lr: 
    values: [1e-5, 1e-4, 1e-3, 2e-3, 1e-2]  # Merged with new `lr` values
  batch_size_per_chain:
    values: [16, 32]  # Merged with new batch sizes
  num_chains:
    values: [16, 32]
  sequence_length:
    values: [512]  # Merged with new sequence lengths
  iterations:
    values: [10000]
  seed:
    values: [1]
  device:
    values: ["cuda:1"]
  opt:
    values: ["adamw", "sgd"]  # Merged with new optimizer values
  warmup_percent:
    values: [0.0, 0.01, 0.02, 0.05, 0.1]
  weight_decay:
    values: [1e-5, 1e-4, 1e-3, 1e-2]
  dropout:
    values: [0.0, 0.1, 0.2, 0.5]
  scheduler:
    values: ["linear", "cos", "none"]
  beta1:
    values: [0.85, 0.9, 0.95]
  beta2:
    values: [0.9, 0.95, 0.999]
  grad_clip:
    values: [0.0, 0.5, 1.0, 2.0, 5.0]

command:
  - python
  - src/main.py
  - ${args}
