name: "markov_llm_depth_heads"
method: grid
project: "markov-LLM-depth-heads-attention-ICL_P_Random-optimised-modified-6th_Oct"
parameters:
  chain:
    values: ["icl"]
  order:
    values: [2]
  n_layer:
    values: [2, 3]
  n_head:
    values: [1]
  n_embd:
    values: [32]
  lr: 
    values: [5e-3, 5e-4, 5e-4]
  batch_size:
    values: [128]
  sequence_length:
    values: [512]
  iterations:
    values: [10000]
  seed:
    values: [1, 2, 3]
  device:
    values: ["cuda:4"] 
  opt:
    values: ["adamw"]

command:
  - python
  - src/main.py
  - ${args}
