name: "markov_llm_depth_heads"
method: grid
project: "markov-LLM-depth-heads-attention-ICL_P_Random-optimised"
parameters:
  chain:
    values: ["icl"]
  order:
    values: [8]
  n_layer:
    values: [2, 3]
  n_head:
    values: [1]
  n_embd:
    values: [16, 32]
  lr: 
    values: [2e-2, 2e-3, 2e-4]
  batch_size:
    values: [128]
  sequence_length:
    values: [512, 256, 128]
  iterations:
    values: [10000]
  seed:
    values: [1, 2, 3]
  device:
    values: ["cuda:3"] 

command:
  - python
  - src/main.py
  - ${args}
